/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_brain4free_jprojectm_ProjectM */

#ifndef _Included_org_brain4free_jprojectm_ProjectM
#define _Included_org_brain4free_jprojectm_ProjectM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_brain4free_jprojectm_ProjectM_init
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_brain4free_jprojectm_ProjectM_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    initJackPorts
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_brain4free_jprojectm_ProjectM_initJackPorts
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    initGlWindow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_brain4free_jprojectm_ProjectM_initGlWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    initTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_brain4free_jprojectm_ProjectM_initTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    initProjectm
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_brain4free_jprojectm_ProjectM_initProjectm
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    initShaders
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_brain4free_jprojectm_ProjectM_initShaders
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    loadPreset
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_brain4free_jprojectm_ProjectM_loadPreset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    destroyJack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_brain4free_jprojectm_ProjectM_destroyJack
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    destroyGl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_brain4free_jprojectm_ProjectM_destroyGl
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    destroyProjectm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_brain4free_jprojectm_ProjectM_destroyProjectm
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_brain4free_jprojectm_ProjectM_render
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    renderTexture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_brain4free_jprojectm_ProjectM_renderTexture
  (JNIEnv *, jobject);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    reshape
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_brain4free_jprojectm_ProjectM_reshape
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_brain4free_jprojectm_ProjectM
 * Method:    startMainLoop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_brain4free_jprojectm_ProjectM_startMainLoop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
